resources:
   - name: u16
     type: gitRepo
     repoPath: ranjansingh41/u16
     configuration:
        integrationName: github
        branches:
           only: master
        tags:
           except: none
           only: none   
        buildOnCommit: true
     initialVersion:
       sha: master
       
pipelines:
  - name: test_pipeline_1
    setup:
      environmentVariables:
        normal:
          - ENV1: value-pipe-1
          - ENV2: value-pipe-2
       
     runtime: 
       type: onHost-pipe
    steps:
      - name: in_trigger_step
        type: bash
        configuration:
          affinityGroup: test_group 
        setup:
          environmentVariables:
            normal:
              - ENV1: value1
              - ENV2: value2
          runtime: host
        execution:
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
         
        triggeredBy:
          resources:
            - u16
        
